### ISSUE TITLE
ngConf2017 Angular Material Workshop

### ISSUE THREAD

**Issue by devversion** [joeeames/ngDocIO_Issues#12]
Hey there,

I just came across http://ngdoc.io and I realized that the link to the Angular Material workshop from NG-Conf 2017 is not valid anymore.

The workshop video has been re-uploaded to remove all the dead time while workshop participants work on their app.

Here is the new link - https://www.youtube.com/watch?v=kyctjcy0CdA

**Comment by sonicparke** [comment]
@DevVersion Thanks! It should be good now.

**Comment by devversion** [comment]
Awesome. Thanks for the quick update!
