### ISSUE TITLE
Add support of saving selected tag state in URL. 

### ISSUE THREAD

**Issue by TerryMooreII** [joeeames/ngDocIO_Issues#4]
I cant IM/email/tweet a filtered state to a co-worker.  I would be nice if I could just send the URL with the query params set for selected tags instead of telling them to click upgrade, then ng-upgrade to see those specific articles.

**Comment by joeeames** [comment]
oh, great idea! I'll put this on the list. Should be fairly easy. Probably take a week or two since I've got a couple higher priority items, but I really like this idea.  Also be nice to have a convenient tweet link that would tweet the current filter state.

**Comment by TerryMooreII** [comment]
How come this isnt open sourced because if it was I would be happy to help where I could.
