### ISSUE TITLE
List Icon should not get the underline on hover

### ISSUE THREAD

**Issue by TerryMooreII** [joeeames/ngDocIO_Issues#5]
I like the new list view however the icon shouldnt receive the link underline like the list items do on hover

<img width="372" alt="screen shot 2017-04-25 at 3 24 44 pm" src="https://cloud.githubusercontent.com/assets/602825/25403771/7ad01f62-29cb-11e7-8ff1-1854d17352da.png">

**Comment by joeeames** [comment]
this is published now.
